feat: Выполнил задание 6 спринта, написал тесты и доп задачу.
prit4er/java-kanban pull request #1
Opened 2024-09-08 14:04 UTC by prit4er

2024-09-09 07:32 UTC, tomattman requested changes
Привет,  у тебя какая то путаница в папках и пакетах, оставил пару коментов, они вроде как все что надо поправить покрывают, 
А по коду, все отлично

2024-09-09 07:32 UTC, tomattman commented on test/HistoryManagerTests.java
> +package test.history;
По структуре пакетов, обычно есть папка src (source) в ней хранится весь код, 
в ней папки main и test в main основной код приложения и в test тесты
а уже  в этих папках одинаковая структура пакетов, т.е. если ты тестируешь класс managers/history то его тест должен быть в папке test и там уже в пакете managers/history

2024-09-09 07:32 UTC, tomattman commented on src/main/managers/java/historyManager/HistoryManager.java
> +package main.managers.java.historyManager;
пакет java стоит удалить из структуры
в проектах который билдаются мейвеном есть определенная структура папок
там основная папка для кода это src/main/java но ни одна из этих папок не является пакетом и не отображается в импортах

2024-09-09 08:48 UTC, prit4er commented on test/HistoryManagerTests.java
> +package test.history;
Я понимаю, что это максимально криво выглядит)
Но не придумал как обойти CheckStyle, он по скриптам запрашивает find: ‘./test’:
И не нашел способа, заставить его смотреть на test директорию, если она будет лежать в src
<img width="1512" alt="Снимок экрана 2024-09-09 в 11 42 32" src="https://github.com/user-attachments/assets/7f747ddb-dd0a-4325-8b4c-b92c97807381">

2024-09-10 14:03 UTC, prit4er commented on src/main/managers/java/historyManager/HistoryManager.java
> +package main.managers.java.historyManager;
удалил java пакет

2024-09-10 18:35 UTC, tomattman approved these changes
еще рекомендация по пакетам, но можно будет поправить к следующией итерации
1) делать базовый общий пакет, например с названием проекта, чтобы в папке main была общий пакет, а уже в нем было разбиение дальше
2) HistoryManager у тебя условно в пакете managers.historyManager а его тест в history
лучше делать идентичную стрктуру
3) тe тебя есть пакет managers а в нем пакет historyManager и taskManager
во первых разный стиль, я рекомендую использовать везде в единственном числе
во вторых получается тафталогия все что в пакете manager так или иначе связано с менеджерами так что внутренние пакеты достаточно было назвать task и history ведь в пути уже есть manager

рекомендую все это поправить к следующей итерации

2024-09-17 14:59 UTC, merged