feat: Выполнил задание 7 спринта, написал тесты и доп задачу.
prit4er/java-kanban pull request #2
Opened 2024-09-27 15:45 UTC by prit4er

2024-09-28 13:33 UTC, tomattman requested changes
Отличная работа, в основном есть моменты на улучшение

2024-09-28 13:33 UTC, tomattman commented on src/main/managers/task/FileBackedTaskManager.java
> +package main.managers.task;
я бы рекомендовал тут разбить по пакетам, и то что касается файлового таскового менеджера закинуть в отдельный

2024-09-28 13:33 UTC, tomattman commented on src/main/managers/task/FileBackedTaskManager.java
> +    public void save() {
этот метод должен быть приватным
Чаще всего когда мы используем класс по интерфейсу, есть простое правило, публичные методы только те, которые есть в интерфейсе

2024-09-28 13:33 UTC, tomattman commented on src/main/managers/task/FileBackedTaskManager.java
> +    public FileBackedTaskManager(File file) {
конструктор я рекомендую сделать приватным, так он останется доступным в статическом методе, но не будет доступен извне, и следовательно обьект класса можно будет создать только через статический метод, т.е. только со считыванием из файла

2024-09-28 13:33 UTC, tomattman commented on src/main/managers/task/FileBackedTaskManager.java
> +    public static String toString(Task task) {
1) этот метод не должен быть публичным
2) я бы рекомендовал сделать класс конвертер который будет уметь превращать обьект в строку для csv, так если появится еще один формат, то модно будет подменить конвертер (да и все преобразования будут в одном месте)
3) не рекомендую называть методы с такими же именами, как методы класса Object чtобы не возникло путаницы, лучше назвать taskToString

2024-09-28 13:33 UTC, tomattman commented on src/main/managers/task/FileBackedTaskManager.java
> +        if (task instanceof Subtask) {
instanceof это не jjg gjl[jl вместо него стоит использовать перегрузку методов, один принимает task и конвертирует в строку task второй принимает subtask

2024-09-28 13:33 UTC, tomattman commented on src/main/managers/task/FileBackedTaskManager.java
> +        super.addTask(task);
тут  все хорошо, но есть одна маленькая потенциальная проблема (исправлять не надо но для задуматься)
если в родительском методе мы не изменяем обьект из параметра, а делаем его копию, то может получиться так, что вернем, обьект без идентификатора

2024-09-28 13:33 UTC, tomattman commented on src/main/model/Task.java
> +    public void updateFrom(Task updatedTask) {
обычно в классы моделей стараются не добавлять никакой логики
только геттеры и сеттеры
делают так, чтобы знать где что реализуется, и не было путаницы (модель только для хранения данных, вся обработка в сервисе (в данном случае в менеджере))

2024-09-28 13:33 UTC, tomattman commented on src/test/tasks/FileBackedTaskManagerTest.java
> +public class FileBackedTaskManagerTest {
хороший способ протестировать файловый таск менеджер, это унаследоваться от теста менеджера в памяти, и переопределить метод, который в переменную manager записывает нужный тип менеджера 
так получатся что применятся все те же тесты что и для менеджера, плюс можно добавить парочку новых, для нового функционала

2024-09-28 16:05 UTC, prit4er commented
Короче, я хз что делать с тестами
Первый комит где папка test лежит в src прошел каким то чудом.

Я прекрасно понимаю, что это решение которое в будущем будет для мавена и гредла одним, 
**НО**
**Сейчас ничего не помогает**, если я не создают test директорию в корне проекта.
Чек стайл просто не пропускает такое

2024-09-29 12:31 UTC, tomattman requested changes
ПРивет, один момент еще надо поправить обязательно, с instanceof остальные больше как рекомендации

2024-09-29 12:31 UTC, tomattman commented on src/main/managers/task/fileBacked/FileBackedTaskManager.java
> +package main.managers.task.fileBacked;
не стоит сильно усложнять имена пакетов, обычно хватает какого то минимального признака
простой пример
main.manager.task.file;
первый пакет main тут это специфика проекта но обычно в корне идет название проекта с доменным именем (это будет более понятно в слдеющем проекте) для уникальности имен классов
manager - тут одно поправление , лучше называть в единственном числе, мы понимаем, что в этом пакете будут менеджеры и что их касается
task значит что тут будут только тасковые менеджеры
file - тут только те что работают с файлами
и в итоге понятно что в этом пакете будут тасковые менеджеры, которые работают с файлами, ну и то что их касается

2024-09-29 12:31 UTC, tomattman commented on src/main/managers/task/fileBacked/FileBackedTaskManager.java
> +    public static class CsvTaskConverter {
этот класс, можно вынести в отдельный файл, зачем перегружать текущий

2024-09-29 12:31 UTC, tomattman commented on src/main/managers/task/fileBacked/FileBackedTaskManager.java
> +            if (task instanceof Subtask) {
вот это надо поправить, повторюсь,
instanceof не ооп подход, следует сделать через перегрузку методов

2024-09-29 14:18 UTC, prit4er commented on src/main/managers/task/fileBacked/FileBackedTaskManager.java
> +package main.managers.task.fileBacked;
+

2024-09-29 14:21 UTC, prit4er commented on src/main/managers/task/fileBacked/FileBackedTaskManager.java
> +            if (task instanceof Subtask) {
Попытался сделать через перегрузку методов, понял, что как то много дублирования получается поэтому,
Решил оформить через полиморфизм

2024-09-30 13:00 UTC, tomattman requested changes
Еще немножечко

2024-09-30 13:00 UTC, tomattman commented on src/main/manager/task/file/CsvTaskConverter.java
> +        return task.toCsvString();
ты же специально создал этот класс, для того чтобы тут контролировать перевод в строку, стоит всю эту логику сделать именно здесь
и именно здесь сделать два метода 
public static String taskToString(Task task)
public static String taskToString(Subtask task)
в которых реализовать разный перевод в строку

2024-09-30 13:00 UTC, tomattman commented on src/main/manager/task/file/CsvTaskConverter.java
> +        return task.toCsvString();
кстати как улучшение после этого, так как все данные о формате в этом классе будут, сюда так же можно добавить метод, который будет возвращать строку заголовок csv файла, так вся структура будет здесь

2024-09-30 13:00 UTC, tomattman commented on src/main/managers/task/fileBacked/FileBackedTaskManager.java
> +            if (task instanceof Subtask) {
не лучше решение добавлять логику в класс модель, так при росте проекта можно потом не найти где и какая логика реализовывается
если хочешь избежать дублирования кода вообще то есть простые решения
они почти одинаковы, но второй требует чуть больше понимания в реализации, но это задачка на подумать

public static String taskToString(Task task)
public static String taskToString(Subtask task)
и тот метод который принимает в себе сабтаск должен вызвать первый, а потом к результату добавить запятую и id эпика

понимания требует то, как вызвать другой метод не изменяя сигнатуры

вариант попроще точно такой же, но все преобразование будет в третьем приватном методе, каждый из указанных выше будет вызывать его, но тот который работает с таском просто возвращать значение, тот который с сабтаском добавлять еще идентификатор эпика

разница в двух подходах только в том, что в первом случае, первый метод играет роль сразу двух этих методов

2024-10-05 09:34 UTC, tomattman approved these changes
Принято

2024-10-05 09:34 UTC, tomattman commented on src/main/manager/task/file/CsvTaskConverter.java
> +    public static String taskToString(Epic epic) {
для эпика можно было не создавать, так как логика от таска не отличается, то при отсуттствии метода для эпика вызывался метод для ближайшего предка - таска

2024-10-05 14:43 UTC, merged