feat: Выполнил задание 8 спринта, написал тесты и доп задачу
prit4er/java-kanban pull request #3
Opened 2024-10-19 03:47 UTC by prit4er

2024-10-19 10:53 UTC, tomattman requested changes
по сути не выполнено

2024-10-19 10:53 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +        for (int i = 0; i < 365 * 24 * 60 / TIME_INTERVAL; i++) {
это плохое решение, 
1) у нас пустой таск менеджер, и уже в нем есть 365 * 24 * 60 /15 = 35040 значений
2) у нас таск менеджер к которого есть только одна задача но она длится год, и в ней, все те же 35040 значений
3) а что если я захочу интервал в 1 минуту?

зачем это если время старта и время окончания уже хранится в обьекте, и тебе надо иметь отсортированный список обьектов

2024-10-19 10:53 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
>          task.setId(generateId());
по условию должна быть проверка на то, что таски не пересекаются, где она,

2024-10-19 10:53 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        removeFromPrioritizedTasks(task); // Удаляем старую версию задачи из отсортированного списка
при обновлении стоит тоже проводить проверку на пересечение

2024-10-19 10:53 UTC, tomattman commented on src/main/model/Epic.java
> +    private Duration duration;
продолжительность и время старта уже есть так как мы наследуемся от таска, стоит добавлять только время окончания

2024-10-19 10:53 UTC, tomattman commented on src/main/model/Epic.java
> +    public void recalculateEpicFields() {
почему этот метод здесь, а не рядом с методом который считает статус эпика

2024-10-19 10:53 UTC, tomattman commented on src/main/model/Epic.java
> +    public void recalculateEpicFields() {
ведь оп сути этот и тот метод, будут всегда вызываться парами

2024-10-19 10:53 UTC, tomattman commented on src/main/model/Epic.java
> +        return new ArrayList<>();
хмм, я уже выше написал коммент, но интересно как это планировалось реализовать, ну и не реализовано же

2024-10-23 10:01 UTC, prit4er commented
Постарался все поправить, но я как будто где то сильно запутался 
тогда наверное ветку пересоздам и новый ПР буду делать(

2024-10-24 09:19 UTC, tomattman requested changes
Привет, добавил много комментариев на улучшение
и все еще есть парочка моментов которые обязательны к исправлению

Основная логика следующая -> у тебя не может быть в одно время сабтасков и тасков, и если они пересекаются, то значит что то не так, и мы должны что то с этим сделать

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/file/FileBackedTaskManager.java
> +    public void addTask(Task task) {
немного не понятно зачем надо было это изменять, предыдущий варинат кажется лучше гораздо

2024-10-24 09:19 UTC, tomattman commented on src/main/model/Task.java
> +    protected int id;
лучше было бы оставить обертку

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private boolean areTimeIntervalsOverlapping(LocalDateTime start1, LocalDateTime end1, LocalDateTime start2, LocalDateTime end2) {
в этом случае рекомендую сделать следующее:
1) сделать чтобы метод принимал два таска вместо 4 дат, так меньше шансов запутаться в параметрах, а уже у тасков внутри метода получить время старта и время окончания (сейчас у тебя есть 4 параметра одного типа, порядок которых важен, так будет два параметра одного типа, порядок которых не важен)
2) в соответствии с этим переименовать метод

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskManager.java
> +
должен появиться метод возвращающий список приоритезированных тасков

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        if (task.getStartTime() == null || task.getEndTime() == null) {
кажется такого условия не было 
даже наоборот в условии прописано что время старта и окончания может быть и не задано

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        for (Task existingTask : tasks.values()) {
вот тут могу предложить несколько улучшений
1) (обязательное) пересечений не должной быть не только по таскам но и по сабтаскам
2) проверку на пересечения можно вынечти в отдлеьный метод, так как логика поиска пересечения будет везде одинаковая
3) время старта может быть не задано, и если оно не задано, пересечения в любом случае не будет, следовательно на них можно и не проверять

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        return addTaskToMap(epics, epic); // Добавление эпика
тут нельзя использовтаь этот метод, потому что эпики не должны попадать в список приоритезированных тасков
1) это есть в условии
2) эпики всегда будут пересекаться со своими сабтасками по времени

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        for (Subtask existingSubtask : getSubtasksByEpic(epic.getId())) {
почему сабтаски проверяются только по сабтаском этого же эпика?

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        for (Task existingTask : tasks.values()) {
почти полное дублирование кода с проверкой при создании
лучше сделать один метод, который будет работать для всех одинаково, и проверять идентифкатор и переиспользовать его (при создании никогда не будет одинаковых идентифкаторов)

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            for (Subtask existingSubtask : getSubtasksByEpic(epic.getId())) {
аналогично с несколькими коментами выше

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            }
куда делось обновление данных эпика?

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        Epic updatedEpic = updateTaskInMap(epics, epic); // Обновление эпика
аналогично с комментарием где то выше, для эпика нельзя использовать тот же метод, потому что эпики не должны попадать в списко приоритезированных тасков

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> -    private void updateEpicStatus(Epic epic) {
а куда этот метод? его можно было оставить

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    public void deleteTaskById(int id) {
специально проверил,мало ли проблемы с отобрадением изменений, но нет
А где тело метода? и двух слудеющих

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +                updateEpicStatus(epic.getId()); // Обновление статуса эпика
надо также обновлять время старта финиша и продолжитлеьность

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private void updateEpicFields(Epic epic) {
этот метод должен вызываться каждый раз, когда изменяются сабтаски эпика и при создании эпика
то что он вызывается при апдейте эпика - не обязательно, но хороший вариант, потому что данные могли быть изменены вручную,  и чтобы хранить корректные значения хорошо пересчитать

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private void updateEpicFields(Epic epic) {
второй момент но он как улучшение
обновление этих полей,  будет всегда происходить вместе с обновление статуса эпика
и чтобы избежать дублирования кода, где каждый раз будут вызываться два метода, можно создать дополнительный приватный метод, который просто внутри себя будет вызывать эти два

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private void updateEpicFields(Epic epic) {
кстати метод бы тоже переименовать, потому что статус это тоже поле эпика, и это может вводить в заблуждение
почему бы не дать более точное имя, например updateEpicPeriod

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private void addToHistory(Epic epic) {
зачем нужны эти два метода, чем они отличаются от первого?

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +public class TaskScheduler {
не заметил что задание немного изменилось, и теперь понял зачем этот класс)

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +        LocalDateTime endTime = startTime.plus(duration);
зачем тут эта переменная если она не используется?

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +public class TaskScheduler {
тут буду писать общие комментарии к этому классу

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +public class TaskScheduler {
так как имеется завязка на продолжительность слота времени, рекомендую вынести его в константу и переиспользовать

такие значения которые используются в коде, называют магическими числами и с ними две проблемы
1) через какое то время ты можешь заглянуть в код и не поймешь что оно значит, когда у тебя есть константа, то по имени константы можно понять для чего она
2) иногда прихоодится такие значения менять, но когда в коде много завязок на это значнеие, и оно используется не из константы, можно забыть поменять в каком то месте, и все сломается

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +            if (isSlotFree == null || !isSlotFree) {
вот тут какой то просчет в логике
1) создали новый обьект TaskScheduler мапа timeSlots пустая
2) проверяем любое время, и так как мапа пустая, то timeSlots.get(slot); всегда будет null а следовательно на проверке isSlotFree == null всегда будет true и знаичт слот всегда занят

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +    private final List<Task> tasks;
зачем тут эта переменная?

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +        for (long i = 0; i < totalSlots; i++) {
и тут мне кажется лучше бы подошел цикл while
public boolean isTimeAvailable(LocalDateTime startTime, Duration duration) {
    LocalDateTime endTime = startTime.plus(duration);
    while(startTime .isBefore(endTime)){
        //делаем проверку  
        startTime = startTime.plusMinutes(15) 
    }
    return true;
}

2024-10-24 09:19 UTC, tomattman commented on src/main/manager/task/TaskScheduler.java
> +        for (long i = 0; i < totalSlots; i++) {
меньше всяких калькуляций со временем

2024-10-24 09:19 UTC, tomattman commented on src/test/EpicStatusTests.java
> +public class EpicStatusTests {
лучше чтобы тесты из этого класса были частью теста inMemoryTaskManager

2024-10-24 09:19 UTC, tomattman commented on src/test/task/TaskManagerTests.java
> +    }
Сюда бы добавить еще тестов на работу с пересечением

2024-10-24 09:19 UTC, tomattman commented on src/test/task/TaskManagerTests.java
> +    private TaskManager taskManager;
отлично сделано, можно еще немного улучшить (это прям очень по желанию)
1) делаем абстрактный тестовый класс - TaskManagerTest
2) в него переносим все содержимое этого класса кроме метода init, его делаем абстрактным
3) делаем класс InMemeryTaskManagerTest, наследуем его от TaskManagerTests и имплементим в нем метод init как в этом классе

в итоге чуть чуть меняется структура, но она становится понятнее и логичнее

2024-10-24 09:19 UTC, tomattman commented on test/EpicStatusTests.java
> +package test;
тут дублируется много классов, стоит оставить только один экземпляр

2024-10-25 13:23 UTC, prit4er commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        for (Subtask existingSubtask : getSubtasksByEpic(epic.getId())) {
Кажется что, подзадачи проверяются только по другим подзадачам того же эпика, потому что каждая подзадача относится к своему конкретному эпику, и логично, что их сроки выполнения и время выполнения должны учитывать только взаимосвязанные задачи

2024-10-25 15:32 UTC, prit4er commented
Вроде все учел, лишнее убрал, тесты добавил

2024-10-26 10:13 UTC, tomattman requested changes
привет, надо все еще много чего поправить, основные моменты в менеджере в памяти
моя рекомендация, пройдись по классу, и в начале помести все методы которые есть в интерфейсе,
потом пройдись по остальным методам, и посмотри, какие из них дублируются, и удали дубликаты
потом пройдись сннова и подумай, можно ли вместо двух похожишь методов без переусложнения сделать один

ну и еще одна рекомендация, если комментарии по функционалу, стоит написать на этот комментарий тест

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        for (Task existingTask : tasks.values()) {
смотри, у тебя сабтаски и таски хранятся в списке приоритезированных, можно было просто по списку приоритезированных смотреть, плюс можно так оптимизировать ведь они там по времени отсортированы

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private boolean taskTimesOverlap(Task existingTask, Task newTask) {
к методам возвращающим boolean лучше в начале добавлять что то что показывает условие, как например в другом методе are

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        return existingTask.getStartTime().isBefore(newEndTime) &&
забыто одно важное условие, проверить идентификатор, если они совпадают то таск не пересекается, иначе таск при обновлении если время не изменено будет всегда пересекаться сам с собой

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            for (T otherTask : taskMap.values()) {
так, у тебя тут хаос в логике, так как это только вторая итерация я отправлю на доработку, просто чтобы его поправить, то что надо поправить обязательно, будет начинаться с порядкового номера, не обращай внимания на порядок, я примерно в таком лажу по коду)))

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            for (T otherTask : taskMap.values()) {
1) у тебя уже есть метод который проверяет пересечения, поему бы его не пере использовать 
по сути для тебя нету разницы при проверке пересечений когда новый таск, и когда существующий, одно отличие - сверка айдишника, но его можно добавить в проверку пересечений нового, ведь там оно ничего значить не будет, новый таск ни с одним по идентификатору не пересечется

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            for (T otherTask : taskMap.values()) {
2) в методе который проверяет пересечение для нового я оставил комментарий про то, что лучше итерироваться один раз по списку приоритезированных

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            if (existingTask instanceof Epic) {
3) instanceof не используем
это не ооп подход, ооп подход это использовать например перегрузку методов

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private void checkForTaskAndSubtaskConflicts(Task newTask) {
4) я не понимаю зачем нужен этот метод, по сути у тебя есть  hasTimeConflict который будет работать и для сабтасков и для тасков

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        if (newTask instanceof Subtask) {
5) этот блок кода вообще не нужен
во первых снова  instanceof не ооп подход
во вторых если сабтаск не пересекается ни с одним таском и сабтаском во всем списке, то он и не пересекается ни с одним сабтаском у эпика

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        LocalDateTime existingEndTime = existingTask.getStartTime().plus(existingTask.getDuration());
6) к тебя у класса Task есть метод, который возвращает время окончания, зачем ты снова реализуешь эту логику здесь

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        for (Task existingTask : tasks.values()) {
2) номер уже был, но добавлю тут
один цикл по списку приоритезированных, проверит пересечение сразу со всеми существующими

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        return existingTask.getStartTime().isBefore(newEndTime) &&
7) этот как раз к этому комменту, по хорошему надо всякие условия проверять в нужных местах
в этом методе ты проверяешь пересечение двух тасок следовательно лучше всего первым действием в этом методе проверить на одинаковые айдишники

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private boolean areTimeIntervalsOverlapping(Task task1, Task task2) {
снова методы дублируются, зачем?

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private boolean areTimeIntervalsOverlapping(Task task1, Task task2) {
что то надо удалить

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        return Optional.ofNullable(tasks.get(id)); // Возвращает задачу по ID или пустое значение
8) а куда делось добавление в историю

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        if (hasTimeConflict(task)) {
9) можно переименовать метод hasTimeConflict в (извиняюсь у меня комп тупит не хочет на английскую раскладку переходить поэтому буду писать русскими буквами) чекТаймКонфликт
и кидать ошибку сразу в нем, ведь везде где будет проверяться конфликт, будет кидаться ошибка

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        prioritizedTasks.add(addedSubtask); // Добавление подзадачи в приоритезированный список
10) обновить время окончания у эпика

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        return Optional.ofNullable(tasks.get(id)); // Возвращает задачу по ID или пустое значение
и у тебя уже есть метод для получение одного таска по идентификатору, оставить надо только один

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            for (Subtask existingSubtask : getSubtasksByEpic(epic.getId())) {
11) у тебя есть метод на проверку пересечений, надо его использовать а это проверка не нужна

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        Subtask oldSubtask = subtasks.get(subtask.getId()); // Получение старой версии подзадачи
12. если сабтаск не найден, то следует кидать ошибку

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        Subtask oldSubtask = subtasks.get(subtask.getId()); // Получение старой версии подзадачи
как ты его можешь обновлять ели его нету

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        removeEpic(id);
снав какое то ненужно размножение методов, зачем тебе метод, который просто вызывает другой метод

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        epics.clear(); // Очистка эпиков
12. когда удаляются все эпики должны ужаляться и все сабтаски, потому что сабтаски не могут существовать без эпика

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        tasks.clear(); // Очистка задач
13. не забудь почистить историю и список приоритезированных тасков

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        return List.of();
14) посмотри сюда еще раз, что он возвращает

2024-10-26 10:13 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    // Общий метод добавления задач, эпиков и подзадач в Map
ты уверен что тебе нужны эти два метода,  может лучше просто напрямую из методов на добавление добавлять данные в мапу, тут это кажется немного пере усложнением

2024-10-27 10:09 UTC, tomattman requested changes
Привет, еще раз, внимательнее,
это уже четвертая итерация
рекомендую на все комменты что я оставил написать тест, и написать его перед тем как исправлять, чтобы он сначала не исполнялся, а потом исправить основной код, чтобы тест заработал

Напомню основные требования
1) если таски или сабтаски (новые и обноновляемые) пересекаются с уже существубшими (но не сами с собой) то кидаем ошибку и не обрабатываем дальше
2)если что то удаляем то удаляем везде, из истории и списка приоритезированных
3)эпики к отсортированным не добавляем, потому что в отсортированном списке только непересекающиеся объекты, а эпики всегда пересекаются со своими сабтасками
4) когда работаем с сабтасками, помним, что сабтаск не может существовать без эпика, и эпик от него зависит (статусом, временам выполнения, и идентификатором в списке сабтасков)
5) когда работаем с эпиком, а именно при удалении, помним, что сабтаск не может существовать без эпика, и сабтаски следует удалять то же

Еще раз, внимательнее пожадуйста

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/history/InMemoryHistoryManager.java
> +        history.clear(); // Очистка истории задач
кажется по условию нету ни одного случая когда должна очищаться вся история, у нас очищаются либо эпики сабтаски, либо сабтаски, либо таски, и если очищено что то одно, то все остальное должно остаться

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/TaskManager.java
> +    void updateTask(Task task);       // Возвращает обновленный Task
комментарии то не в тему, а это очень сбивает, метод же ничего не возвращает

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private boolean checkTimeConflict(Task newTask) {
отлично

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    private boolean checkTimeConflict(Task newTask) {
* единственная рекомендация, это чтобы метод не возвращал true false  а сам сразу кидал ошибку

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            if (existingTask.getId() != newTask.getId() && areTasksOverlapping(existingTask, newTask)) {
* у тебя функционал дублируется в двух местах, сначала тут сверяем идентификаторы потом еще в методе areTasksOverlapping рекомендую сделать только в этом методе, так он будет более универсальным

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        if (checkTimeConflict(task)) {
тут смотри какой момент и он относится больше к методу  checkTimeConflict но тут комментарий будет нагляднее

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        if (checkTimeConflict(task)) {
1)обычно методы которые что то возвращают имеют в начале либо get либо is (ну или are) и то что они возвращают например isTimeOverlap 
конкретно в этом случае имя checkTimeConflict и по логике вся проверка должна проходить внутри метода, ведь метод должен сам проверить временной конфликт

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        if (checkTimeConflict(task)) {
2) у тебя будет везде на проверке комбинация 
если конфликт то кинуть ошибку, так вот это условие можно закинуть в метод и тогда во всех местах код будт выглядеть следующим образом

checkTimeConflict(task)

и все, если конфликт есть, летит ошибка, выполнение дальше не идет, если ошибки нету, то значит конфликта нету, работаем дальше

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/TaskManager.java
> +    void updateTask(Task task);       // Возвращает обновленный Task
плюс создание возвращает апдейт нет, тоже не логично

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/TaskManager.java
> +    void updateTask(Task task);       // Возвращает обновленный Task
лучше сделать чтобы значение возвращалось

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        addToPrioritizedTasks(epic); // Добавляем задачу в отсортированный список
* эпики мы не добавляем в отсортированный список, потому, что эпики всегда пересекаются со своими сабтасками ( если есть время выполнения)

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        addToPrioritizedTasks(epic); // Добавляем задачу в отсортированный список
второй момент, стоит вызвать метод на обновление статуса и времени выполнения
таким образом после добавления всегда будет правильный статус и время выполнения (ведь я могу перед добавлением проставить эпику статус отличный от правильного, и все, он у нас хранится не правильным

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        updateEpicStatus(epic.getId()); // Обновление статуса эпика
тут комент больше про эти методы
но смотри, один принимает id а второй - сам эпик, а делают по сути одно и то же, так почему такая разница
следует сделать чтобы оба принимали одно и то же

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        Epic epic = epics.get(subtask.getEpicId());
стоит проверить что он не null ведь иначае будут ошибки

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            return Collections.emptyList(); // Если эпик не найден, возвращаем пустой список
логичнее если эпик не найден, то кидать ошибку, что эпик не найден

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    public void updateTask(Task task) {
Override лучше оставить

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        checkTimeConflict(task);
пожалуйста к следующей итерации проверь все, а еще лучше на каждый мой коммент с функциональными ошибками писать тест

и вот тебе тот тест который надо написать (что не будет работать поймешь в результате его выполнения)
создаем два таска, без пересечений по времени и добавляем в менеджер
первому устанавливаем время старта и выполнения и пытаемся обновить его в менеджере
ожидаемый результат - падает ошибка а в менеджере остается старая версия таска
поведение сейчас таск обновится без ошибок, и будет у тебя два таска пересекающихся

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            updateEpicPeriod(oldEpic); // Обновление полей эпика при его обновлении
я бы рекомендовал и статус тоже обновлять

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            updateEpicPeriod(oldEpic); // Обновление полей эпика при его обновлении
хотя учитывая что обновляем мы не заменой всего объекта, а его полей, можно даже тайм период не обновлять, ведь он никак не изменится

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        Subtask oldSubtask = subtasks.get(subtask.getId()); // Получение старой версии подзадачи
проверить пересечения

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            checkTimeConflict(subtask);
почему конфликты проверяются только если найден эпик?

надо сделать наоборот, если эпик не найден то кидаем ошибку, иначе обрабатываем

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            checkTimeConflict(subtask);
примерно следующим образом метод должен выглядеть

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            checkTimeConflict(subtask);
public void updateSubtask(Subtask subtask) {
получили старый сабтаск проверили что он существует
(вот тут можно проверить что идентификаторы старого эпика и нового эпика совпадают, если на совпадают, то проще кидать ошибку)
проверили пересечение
получили эпик проверили что он существует
удалили из приоритезированных, обновили поля,
обновили сабтаск в мапе,
добавили сабтаск в приоритезированные
обновили статус и время выполнения эпика

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        oldSubtask.setName(subtask.getName());
зачем тут эти действия, ты обновляешь поля в объекте, который потом нигде не используешь

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            removeFromPrioritizedTasks(task); // Удаление задачи из отсортированного списка
а удалить из истории

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +            Epic epic = epics.get(subtask.getEpicId()); // Получаем эпик
не забудь удалить сабтаск из списка приоритезированных и истории

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +    public void clearTasks() {
очистка тасков, это очистка ТОЛЬКО тасков
из мапы, из списка приоритезированных, из истории

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        List<Integer> subtaskIds = new ArrayList<>();
сабтаски не могут существовать без эпиков
так что тут можно просто подчистить две мапы, а потмо удалить все сабтаски из списка приоритезированных и все сабтаски из истории
ну и эпики из истории

2024-10-27 10:09 UTC, tomattman commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        subtasks.clear(); // Очистка подзадач
также надо удалить их из списка приоритезированных и истории

2024-10-27 12:11 UTC, prit4er commented
Все комментарии поправил, переписал тесты так чтобы точно проверяли

2024-10-27 12:12 UTC, prit4er commented on src/main/manager/task/inMemory/InMemoryTaskManager.java
> +        subtasks.clear(); // Очистка подзадач
готово

2024-10-27 12:22 UTC, prit4er commented on src/main/manager/task/TaskManager.java
> +    void updateTask(Task task);       // Возвращает обновленный Task
я просто убрал комментарии, кажется если я начну возвращать значения, то еще сильнее закопаю себя в ошибках сейчас

2024-10-27 15:29 UTC, tomattman approved these changes
Принято

2024-10-28 03:48 UTC, merged